### ISSUE TITLE
[Managed] Windows SQLite NuGet includes a specific version of runtime dll

### ISSUE THREAD

**Issue by thyeggman** [Azure/azure-mobile-services-test#103]
The windows 8 test project for the managed sdk includes a reference to a specific version of the SQLite NuGet.  If that version of the NuGet isn't installed on your machine then the project won't build.

**Comment by jwallra** [comment]
Looks like this is unavoidable, SQLite PCL needs a specific dll from SQLite to be able to work properly as per conversation with phvannor.  Looking to make a note in the readme about this and point to the SQLite PCL docs.
